226 c4.0
Ericsson/ecaudit pull request #237
Opened 2023-10-17 10:50 UTC by paulchandler

Add audit logs for prepare statements.
#226

2023-10-23 09:18 UTC, tommystendahl requested changes

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
> +    /**
Add empty line above

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditConfig.java
> +    public boolean isSuppressPrepareStatements()
Add empty line above

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
> +    public Boolean isSuppressPrepareStatements()
Add empty line above

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/PrepareAuditOperation.java
> +    @Override
Add empty line above

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
> +
remove one empty line

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
> +
remove empty line

2023-10-23 09:18 UTC, tommystendahl commented on ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
> +
remove empty lines

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
> +//      assertThat(getLogEntries()).containsOnly("client:'127.0.0.1'|user:'anonymous'|status:'ATTEMPT'|operation:'INSERT INTO school.students (key, value) VALUES (?, ?)[42, 'Kalle']'");
remove commented code

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
> +//        verify(mockAuditAppender, never() ).doAppend(loggingEventCaptor.capture());
remove commented code

2023-10-23 11:57 UTC, paulchandler commented
All items fixed

2023-10-25 09:50 UTC, tommystendahl approved these changes

2023-10-25 09:50 UTC, merged