#226 Add auditing for prepare statements
Ericsson/ecaudit pull request #238
Opened 2023-10-18 16:03 UTC by paulchandler

#226

2023-10-23 09:18 UTC, tommystendahl requested changes

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
> +
remove empty line

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/PrepareAuditQueryLogger.java
> +
remove empty line

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/PrepareAuditQueryLogger.java
> +    @Test
Add empty line above

2023-10-23 09:18 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/PrepareAuditQueryLogger.java
> +
remove one empty line

2023-10-24 06:54 UTC, tommystendahl commented on .idea/misc.xml
No, the file is still deleted in the PR. Its deleted in the first commit so I think you have to do a commit that puts the file back.

2023-10-24 06:59 UTC, tommystendahl requested changes

2023-10-24 06:59 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/PrepareAuditOperation.java
> +    @Override
You missed this one.

2023-10-24 06:59 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
> +
Still two empty lines here.

2023-10-24 06:59 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
> +    @Override
and this one

2023-10-24 06:59 UTC, tommystendahl commented on ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
> +
and this one

2023-10-24 06:59 UTC, tommystendahl commented on ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
> +
and here

2023-10-24 06:59 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
> +
and here

2023-10-24 06:59 UTC, tommystendahl commented on integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
> +    @Test
and here

2023-10-24 12:46 UTC, tommystendahl requested changes

2023-10-24 12:46 UTC, tommystendahl commented on .idea/misc.xml
> -<?xml version="1.0" encoding="UTF-8"?>
You missed the first line in the file.

2023-10-25 08:57 UTC, paulchandler commented on .idea/misc.xml
> -<?xml version="1.0" encoding="UTF-8"?>
I have added this back in now.

2023-10-25 09:30 UTC, tommystendahl approved these changes

2023-10-25 09:30 UTC, merged